name: 's3-cache'
description: 'Cache user specified directory to AWS S3'
inputs:
  aws-id: # aws id
    description: 'aws id'
    required: true
  aws-key: # aws key
    description: 'aws-key'
    required: true
  aws-region: # region of aws
    description: 'aws region'
    required: false
    default: 'us-east-1'  
  s3-bucket-root: # aws bucket
    description: 'aws bucket'
    required: true
  bucket_dir:
    description: 'bucket diretory'
    required: true
  cache_key:
    description: 'unique cache key'
    required: true
  zip-filename:
    description: 'zip filename'
    required: false
    default: 'cache.tar'
  dir-to-cache:
    description: 'relative directory to cache'
    required: true
  dir-to-unzip:
    description: 'relative directory to unzip cache'
    required: false
    default: './'
outputs:
  operation:
    description: 'creation / retrieval'
runs:
  using: 'node12'
  main: 'index.js'
  post: 'cleanup.js'